# Clean up temporary files generated by Abaqus.

import os
import glob

def cleanup_abaqus_junk():

    exception_files = glob.glob("*.exception")
    if exception_files:
        return

    extensions = [
        "*.abq", "*.cid", "*.com", "*.ipm", "*.log",
        "*.mdl", "*.pac", "*.prt", "*.res", "*.sel",
        "*.simlog", "*.stt", "*.rpy*", "*.env",
    ]
    for ext in extensions:
        for f in glob.glob(ext):
            os.remove(f)

    # Also clean up two levels above 
    os.chdir("../..")
    for f in glob.glob("*.rec"):
        os.remove(f)
    for f in glob.glob("*.rpy*"):
        if f != "abaqus.rpy":
            os.remove(f)
