# Clean up temporary files generated by Abaqus.

import os
import glob

def cleanup_abaqus_junk(base_dir=None):
    # Remove Abaqus scratch files. 
    # base_dir bounds the cleanup to a single job's run directory for simultaneous job submissions
    prev_cwd = os.getcwd()
    if base_dir is not None:
        try:
            os.chdir(base_dir)
        except OSError:
            pass

    try:
        if glob.glob("*.exception"):
            return

        extensions = [
            "*.abq", "*.cid", "*.com", "*.ipm", "*.log",
            "*.mdl", "*.pac", "*.prt", "*.res", "*.sel",
            "*.simlog", "*.stt", "*.rpy*", "*.env", "*.rec",
        ]
        for ext in extensions:
            for f in glob.glob(ext):
                try:
                    os.remove(f)
                except OSError:
                    pass
    finally:
        try:
            os.chdir(prev_cwd)
        except OSError:
            pass