# Design generator for the Drucker-Prager screening / sweep campaign
# (CPython, not Abaqus).
#
#   python3 generate_design.py                          # all four campaigns
#   python3 generate_design.py glassy_pc --r 12
#   python3 generate_design.py glassy_pc --method sobol --n 1024 \
#           --only X,h,mu_eff,phi
#
# Writes designs/<family>_<method>.csv, read by run_parameter_study.py.

import argparse
import csv
import os
import sys

import numpy as np

try:
    _HERE = os.path.dirname(os.path.abspath(__file__))
except NameError:
    _HERE = os.path.abspath(".")
sys.path.insert(0, os.path.dirname(_HERE))

try:
    from ScratchSimulation.AbaqusModel.Configuration import get_family
    from ScratchSimulation.AbaqusModel.Configuration.sampling import (
        CAMPAIGNS, morris_design, sobol_design)
except ImportError as exc:
    raise SystemExit(
        "Cannot import the Configuration package from %s (%s).\n"
        "Run this script from the ScratchSimulation directory."
        % (os.path.dirname(_HERE), exc))


DEFAULT_R = 10
DEFAULT_LEVELS = 4
DEFAULT_CANDIDATES = 200
DEFAULT_SEED = 42
DEFAULT_OUT = os.path.join(_HERE, "designs")


def _restrict(spec, only):
    if not only:
        return list(spec.factors), {}
    wanted = [s.strip() for s in only.split(",") if s.strip()]
    for name in wanted:
        spec.factor(name)
    active = [f for f in spec.factors if f.name in wanted]
    fixed = dict((f.name, f.mid()) for f in spec.factors if f.name not in wanted)
    return active, fixed


def build_design(family, method="morris", r=DEFAULT_R, n=1024,
                 n_levels=DEFAULT_LEVELS, seed=DEFAULT_SEED,
                 n_candidates=DEFAULT_CANDIDATES, only=None):

    spec = CAMPAIGNS[family]
    cfg = get_family(family).build_config()
    active, fixed = _restrict(spec, only)
    d = len(active)
    if d == 0:
        raise SystemExit("--only left no active factor for '%s'" % family)

    if method == "morris":
        design = morris_design(d, r, n_levels=n_levels, seed=seed,
                               n_candidates=n_candidates)
    elif method == "sobol":
        design = sobol_design(d, n, seed=seed)
    else:
        raise SystemExit("Unknown method '%s' (morris | sobol)" % method)

    unit = design["unit"]
    rows = []
    for i in range(unit.shape[0]):
        groups = dict(fixed)
        for j, f in enumerate(active):
            groups[f.name] = float(f.to_physical(unit[i, j]))
        params = spec.derive(groups, cfg)
        moved = int(design["moved"][i])
        rows.append({
            "id": "%05d" % (i + 1),
            "campaign": spec.campaign,
            "family": family,
            "method": design["method"],
            "traj": int(design["traj"][i]),
            "step": int(design["step"][i]),
            "moved": (active[moved].name if moved >= 0 else ""),
            "sign": float(design["sign"][i]),
            "unit": dict((f.name, float(unit[i, j])) for j, f in enumerate(active)),
            "groups": groups,
            "params": params,
        })
    return spec, cfg, active, fixed, design, rows


def write_design(path, spec, cfg, active, fixed, design, rows):
    group_names = [f.name for f in spec.factors]
    param_names = sorted(rows[0]["params"].keys())
    active_names = [f.name for f in active]

    header = (["id", "campaign", "family", "method", "traj", "step", "moved", "sign"]
              + ["u_%s" % n for n in active_names]
              + ["g_%s" % n for n in group_names]
              + ["p_%s" % n for n in param_names])

    if not os.path.isdir(os.path.dirname(path)):
        os.makedirs(os.path.dirname(path))

    with open(path, "w") as f:
        f.write("# Sweep design -- generated by generate_design.py\n")
        f.write("# campaign=%s family=%s label=%s\n" % (spec.campaign, rows[0]["family"], spec.label))
        f.write("# method=%s n_runs=%d n_factors=%d seed=%d\n"
                % (design["method"], len(rows), design["n_factors"], design["seed"]))
        if design["method"] == "morris":
            f.write("# morris r=%d p=%d delta=%.6f candidates=%d maximin=%.4f\n"
                    % (design["n_trajectories"], design["n_levels"], design["delta"],
                       design["n_candidates"], design["maximin_score"]))
        f.write("# active_factors=%s\n" % ",".join(active_names))
        for fac in active:
            f.write("#   %s in [%g, %g] (%s) %s\n"
                    % (fac.name, fac.lo, fac.hi, fac.scale, fac.description))
        if fixed:
            f.write("# fixed_at_mid=%s\n"
                    % ",".join("%s=%.6g" % (k, v) for k, v in sorted(fixed.items())))
        f.write("# frozen=%s\n"
                % ",".join("%s=%s" % (k, v) for k, v in sorted(spec.frozen.items())))
        f.write("# geometry: tip_radius=%.4g mm cone_angle=%.4g deg scratch_depth=%.4g mm\n"
                % (cfg.indenter.tip_radius, cfg.indenter.cone_angle, cfg.scratch.scratch_depth))
        f.write("# NOTE: p_* columns are traceability only; the Abaqus side re-derives\n"
                "#       them in-kernel from the g_* columns via families.py.\n")

        w = csv.writer(f)
        w.writerow(header)
        for r in rows:
            w.writerow(
                [r["id"], r["campaign"], r["family"], r["method"], r["traj"],
                 r["step"], r["moved"], "%g" % r["sign"]]
                + ["%.10g" % r["unit"][n] for n in active_names]
                + ["%.10g" % r["groups"][n] for n in group_names]
                + ["%.10g" % r["params"][n] for n in param_names])

    print("Wrote %d runs -> %s" % (len(rows), path))


def main():
    ap = argparse.ArgumentParser(description="Generate a screening or sweep design.")
    ap.add_argument("family", nargs="?", default=None,
                    help="campaign host family: %s (both share the unified DP "
                         "campaign, so one design is emitted)" % ", ".join(sorted(CAMPAIGNS)))
    ap.add_argument("--method", default="morris", choices=("morris", "sobol"))
    ap.add_argument("--r", type=int, default=DEFAULT_R, help="Morris trajectories")
    ap.add_argument("--n", type=int, default=1024, help="Sobol samples")
    ap.add_argument("--levels", type=int, default=DEFAULT_LEVELS, help="Morris grid levels (even)")
    ap.add_argument("--candidates", type=int, default=DEFAULT_CANDIDATES)
    ap.add_argument("--seed", type=int, default=DEFAULT_SEED)
    ap.add_argument("--only", default=None,
                    help="comma-separated factor subset; the rest are frozen at mid-range")
    ap.add_argument("--out-dir", default=DEFAULT_OUT)
    args = ap.parse_args()

    families = [args.family] if args.family else sorted(CAMPAIGNS)
    if not args.family:
        # Several families can share one campaign (the unified DP box); emit it once.
        seen, unique = set(), []
        for fam in families:
            key = CAMPAIGNS[fam].campaign
            if key not in seen:
                seen.add(key)
                unique.append(fam)
        families = unique
    for fam in families:
        if fam not in CAMPAIGNS:
            raise SystemExit("No campaign for family '%s' (hosts: %s)"
                             % (fam, ", ".join(sorted(CAMPAIGNS))))
        spec, cfg, active, fixed, design, rows = build_design(
            fam, method=args.method, r=args.r, n=args.n, n_levels=args.levels,
            seed=args.seed, n_candidates=args.candidates, only=args.only)
        path = os.path.join(args.out_dir, "%s_%s.csv" % (fam, args.method))
        write_design(path, spec, cfg, active, fixed, design, rows)
        print("   campaign %s | d=%d | %d runs" % (spec.campaign, len(active), len(rows)))


if __name__ == "__main__":
    main()