# -*- coding: utf-8 -*-
# Multi-job launcher for ScratchSimulation.

# "python3 launch_cluster_jobs.py" (from the ScratchSimulation directory)

# For every JOBS: 
#  job_<label>.py - driver that runs run_parameter_study                           
#  submit_<label>.sh - copy of submit.sh with 'job_<label>'

import os
import re
import subprocess
import sys
import time


# Configuration: (study, family) or (study, family, opts)
#   opts (dict, optional):
#     "tag": free variant name -> job label <study>_<family>_<tag> and
#            ISOLATED run dir runs/<Study>_<family>_<tag> (mandatory when the
#            same (study, family) appears several times: the duplicate-label
#            check rejects untagged twins).
#     any other key = per-job config override, forwarded to
#     run_parameter_study.py as a set:<path>=<value> token and applied AFTER
#     the study's configure() (per-job choice wins, e.g. ALE on a mesh study):
#       - friendly aliases: ALE, scratch_time, scratch_depth, scratch_length,
#         mass_scale, target_dt, hourglass   (see _OVERRIDE_ALIASES below)
#         hourglass accepts DEFAULT / ENHANCED / RELAX STIFFNESS (case- and
#         underscore-insensitive: "relax_stiffness" is normalised).
#       - or any dotted cfg path verbatim, e.g. "solver.ale_frequency": 10
# NB : make sure that the number of jobs * CPUs per job < CPUs of the node 
JOBS = [
    #("mesh", "glassy_pc", {"tag": "mesh3", "ALE": True, "scratch_time": 0.05}),
    #("mesh", "glassy_dp", {"tag": "mesh3", "ALE": True, "scratch_time": 0.05}),
    #("mesh", "glassy_pmma", {"tag": "mesh3", "ALE": True, "scratch_time": 0.05}),
    #("mesh", "semicrystalline_j2", {"tag": "mesh3", "ALE": True, "scratch_time": 0.05}),
    #("mesh", "semicrystalline_dp", {"tag": "mesh3", "ALE": True, "scratch_time": 0.05}),
    #("mesh", "elastomer_mr", {"tag": "mesh3", "ALE": True, "scratch_time": 0.05, "hourglass": "RELAX STIFFNESS"}),
    #("mesh", "elastomer_ve", {"tag": "mesh3", "ALE": True, "scratch_time": 0.05, "hourglass": "RELAX STIFFNESS"}),
    #("mesh", "glassy_pc", {"tag": "mesh2", "ALE": True, "scratch_time": 0.1}),
    #("mesh", "glassy_dp", {"tag": "mesh2", "ALE": True, "scratch_time": 0.1}),
    #("mesh", "glassy_pmma", {"tag": "mesh2", "ALE": True, "scratch_time": 0.1}),
    #("mesh", "semicrystalline_j2", {"tag": "mesh2", "ALE": True, "scratch_time": 0.1}),
    #("mesh", "semicrystalline_dp", {"tag": "mesh2", "ALE": True, "scratch_time": 0.1}),
    #("mesh", "elastomer_mr", {"tag": "mesh2", "ALE": True, "scratch_time": 0.1, "hourglass": "RELAX STIFFNESS"}),
    #("mesh", "elastomer_ve", {"tag": "mesh2", "ALE": True, "scratch_time": 0.1, "hourglass": "RELAX STIFFNESS"}),
    ("mesh", "glassy_dp", {"tag": "ALE20", "ALE": True, "scratch_time": 0.05, "freq": 20, "sweeps": 1}),
    ("mesh", "glassy_dp", {"tag": "ALE200", "ALE": True, "scratch_time": 0.05, "freq": 20, "sweeps": 3}),
    ("mesh", "glassy_dp", {"tag": "ALE650", "ALE": True, "scratch_time": 0.05, "freq": 650, "sweeps": 3}),
    ("mesh", "glassy_dp", {"tag": "ALE1300", "ALE": True, "scratch_time": 0.05, "freq": 1300, "sweeps": 5}),
]
SWEEP_JOBS = 8                  # number of jobs for the "material" sweep 
SUBMIT_TEMPLATE = "submit.sh"
DRY_RUN = False                 # True for testing only


# Valid tokens 
_VALID_STUDIES = ("single", "mesh", "mass_scale", "friction", "material",
                  "models", "depth", "gsell_h", "target_dt")

_VALID_FAMILIES = ("elastomer_mr", "elastomer_ve", "semicrystalline_j2",
                   "semicrystalline_dp", "glassy_dp", "glassy_pc", "glassy_pmma")

DRIVER_TEMPLATE = '''# Auto-generated by launch_cluster_jobs.py -- do not edit (overwritten).
# Job: {label}   Tokens: {tokens}
import sys, os
sys.dont_write_bytecode = True
SCRIPT = {script!r}
sys.path.insert(0, os.path.dirname(os.path.dirname(SCRIPT)))
sys.argv = [SCRIPT, "--"] + {tokens!r}
exec(compile(open(SCRIPT).read(), SCRIPT, "exec"),
     {{"__name__": "__main__", "__file__": SCRIPT}})
'''

def read_template():
    if not os.path.exists(SUBMIT_TEMPLATE):
        raise SystemExit("Template '%s' not found." % SUBMIT_TEMPLATE)
    with open(SUBMIT_TEMPLATE, "rb") as f:
        raw = f.read()
    if b"run_parameter_study" not in raw:
        raise SystemExit("'%s' does not contain the word 'run_parameter_study' " % SUBMIT_TEMPLATE)
    return raw


def wrapper_cpus(raw):
    """Read '-c' from the wrapper line so the Abaqus CPU count follows submit.sh automatically (cpus = token)."""
    m = re.search(rb"run_parameter_study", raw)
    line = raw[:m.start()].rsplit(b"\n", 1)[-1] + raw[m.start():].split(b"\n", 1)[0]
    m = re.search(rb"-c\s+(\d+)", line)
    return int(m.group(1)) if m else None


# Friendly names for per-job overrides; any opts key containing '.' is
# passed through verbatim as a cfg attribute path.
_OVERRIDE_ALIASES = {
    "ALE":            "solver.use_ALE",
    "scratch_time":   "scratch.scratch_time",
    "scratch_depth":  "scratch.scratch_depth",
    "scratch_length": "scratch.scratch_length",
    "mass_scale":     "solver.mass_scale",
    "target_dt":      "solver.target_time_increment",
    "hourglass":      "mesh.hourglass_control",
    "freq":           "solver.ale_frequency",
    "sweeps":         "solver.ale_mesh_sweeps",
}

# mesh_substrate() compares hourglass_control against these EXACT strings and
# silently falls back to DEFAULT on anything else -- so validate here, loudly.
_HOURGLASS_VALUES = ("DEFAULT", "ENHANCED", "RELAX STIFFNESS")


def _normalize_hourglass(value, entry):
    v = str(value).upper().replace("_", " ").strip()
    if v not in _HOURGLASS_VALUES:
        raise SystemExit("Bad hourglass value %r in JOBS entry %r. Valid: %s"
                         % (value, entry, ", ".join(_HOURGLASS_VALUES)))
    return v

_TAG_RE = re.compile(r"^[A-Za-z0-9_.-]+$")   # tag lands in file + job names


def _format_override(value):
    # bool first: isinstance(True, int) is True in Python.
    if isinstance(value, bool):
        return "True" if value else "False"
    return str(value)


def _opt_tokens(opts, entry):
    """opts dict -> (tag or None, ['set:path=value', ...] tokens)."""
    if not isinstance(opts, dict):
        raise SystemExit("Bad JOBS entry %r: third element must be a dict."
                         % (entry,))
    tag = None
    tokens = []
    for key, value in opts.items():
        if key == "tag":
            tag = str(value)
            if not _TAG_RE.match(tag):
                raise SystemExit("Bad tag %r in JOBS entry %r "
                                 "(letters, digits, _ . - only)." % (tag, entry))
            continue
        path = _OVERRIDE_ALIASES.get(key, key if "." in key else None)
        if path is None:
            raise SystemExit(
                "Unknown override key '%s' in JOBS entry %r. Use an alias (%s) "
                "or a dotted cfg path such as 'solver.use_ALE'."
                % (key, entry, ", ".join(sorted(_OVERRIDE_ALIASES))))
        if path == "mesh.hourglass_control":
            value = _normalize_hourglass(value, entry)
        tokens.append("set:%s=%s" % (path, _format_override(value)))
    return tag, tokens


def expand_jobs():
    """JOBS entries -> list of (label, tokens). 'material' is split. Expands
    per-job opts (tag + overrides), validates tokens, rejects duplicate labels."""
    out = []
    for entry in JOBS:
        if len(entry) not in (2, 3):
            raise SystemExit("Bad JOBS entry %r: expected (study, family) or "
                             "(study, family, opts)." % (entry,))
        study, family = entry[0], entry[1]
        opts = entry[2] if len(entry) == 3 else {}
        if study not in _VALID_STUDIES:
            raise SystemExit("Unknown study '%s' in JOBS. Valid: %s"
                             % (study, ", ".join(_VALID_STUDIES)))
        if family not in _VALID_FAMILIES:
            raise SystemExit("Unknown family '%s' in JOBS. Valid: %s"
                             % (family, ", ".join(_VALID_FAMILIES)))
        tag, over = _opt_tokens(opts, entry)
        base_label = "%s_%s" % (study, family) + (("_%s" % tag) if tag else "")
        tag_tok = (["tag=%s" % tag] if tag else [])
        if study == "material" and SWEEP_JOBS > 1:
            for i in range(SWEEP_JOBS):
                label = "%s_c%03dof%03d" % (base_label, i, SWEEP_JOBS)
                out.append((label, [study, family, "%d/%d" % (i, SWEEP_JOBS)]
                            + tag_tok + over))
        else:
            out.append((base_label, [study, family] + tag_tok + over))

    labels = [lbl for lbl, _ in out]
    dups = sorted(set(l for l in labels if labels.count(l) > 1))
    if dups:
        raise SystemExit(
            "Duplicate job label(s) %s -- give each variant a distinct "
            "'tag' in its opts dict." % ", ".join(dups))
    return out


def main():
    raw = read_template()
    cpus = wrapper_cpus(raw)
    here = os.path.abspath(os.path.dirname(os.path.abspath(__file__)))
    script = os.path.join(here, "run_parameter_study.py")

    jobs = expand_jobs()
    print(">>> %d job(s) to submit (template: %s%s)"
          % (len(jobs), SUBMIT_TEMPLATE,
             ", -c %d detected -> cpus token" % cpus if cpus else ""))

    for label, tokens in jobs:
        if cpus:
            tokens = tokens + ["cpus=%d" % cpus]

        # 1. driver
        driver = "job_%s.py" % label
        with open(os.path.join(here, driver), "w") as f:
            f.write(DRIVER_TEMPLATE.format(label=label, tokens=tokens, script=script))

        # 2. submit script ()= submit.sh with the word substituted)
        submit = "submit_%s.sh" % label
        body = raw.replace(b"\r\n", b"\n").replace(b"\r", b"\n")
        body = body.replace(b"run_parameter_study", driver[:-3].encode())
        with open(os.path.join(here, submit), "wb") as f:
            f.write(body)

        # 3. sbatch
        cmd = ["sbatch", submit]
        print("  [%s]  %s" % (label, " ".join(cmd)))
        if not DRY_RUN:
            rc = subprocess.call(cmd, cwd=here)
            if rc != 0:
                print("  !! sbatch returned %d for %s" % (rc, label))
            elif label != jobs[-1][0]:      
                delay = 10                  
                time.sleep(delay)

    if DRY_RUN:
        print(">>> DRY_RUN: files generated, nothing submitted.")
    return 0


if __name__ == "__main__":
    sys.exit(main())

