# -*- coding: utf-8 -*-
# Multi-job launcher for ScratchSimulation.
#
# USAGE (WinSCP console, from the ScratchSimulation directory):
#     python3 launch_cluster_jobs.py
#
# Edit the CONFIGURATION block below, run the line above, done.
#
# WHAT IT DOES
#   For every entry of JOBS this script generates:
#     job_<label>.py      -- a 10-line driver that runs run_parameter_study
#                            with the right tokens (study, family, i/N)
#     submit_<label>.sh   -- a byte-for-byte copy of YOUR submit.sh in which
#                            the word 'run_parameter_study' is replaced by
#                            'job_<label>' (everything else untouched: same
#                            wrapper, same resources, same line endings)
#   and then submits it exactly the way you do by hand:
#     sbatch submit_<label>.sh
#
#   The "material" study (QMC sweep) is automatically split into SWEEP_JOBS
#   independent SLURM jobs, each running the round-robin slice cases[i::N]
#   in its own isolated directory runs/MaterialSweep_c{i}of{N} (unique job
#   names, no .odb/.sta/.lck collisions). Every other study = one job.
#
#   Generated files (job_*.py, submit_*.sh) are overwritten on each launch;
#   add 'job_*.py' and 'submit_*.sh' to .gitignore if desired.

import os
import re
import subprocess
import sys

# ============================ CONFIGURATION =================================
# One entry per job: (study, family). Available studies: single, mesh,
# mass_scale, friction, models, material. Available families: elastomer_mr,
# elastomer_ve, semicrystalline_j2, glassy_dp, glassy_pc, glassy_pmma.
JOBS = [
    ("mesh", "glassy_pc"),
    ("mesh", "glassy_dp"),        
    #("mesh", "glassy_pmma"),
    # ("mesh", "semicrystalline_j2"),
    # ("mass_scale", "glassy_pc"),
    # ("models", "elastomer_mr"),
]

SWEEP_JOBS = 8          # number of SLURM jobs the "material" sweep is split into
SUBMIT_TEMPLATE = "submit.sh"
DRY_RUN = False         # True: generate the files, print the commands, submit nothing
# ============================================================================

# Valid tokens (kept in sync with run_parameter_study.STUDIES / Configuration).
_VALID_STUDIES = ("single", "mesh", "mass_scale", "friction", "material", "models")
_VALID_FAMILIES = ("elastomer_mr", "elastomer_ve", "semicrystalline_j2",
                   "glassy_dp", "glassy_pc", "glassy_pmma")


DRIVER_TEMPLATE = '''# Auto-generated by launch_cluster_jobs.py -- do not edit (overwritten).
# Job: {label}   Tokens: {tokens}
import sys, os
sys.dont_write_bytecode = True
SCRIPT = {script!r}
sys.path.insert(0, os.path.dirname(os.path.dirname(SCRIPT)))
sys.argv = [SCRIPT, "--"] + {tokens!r}
exec(compile(open(SCRIPT).read(), SCRIPT, "exec"),
     {{"__name__": "__main__", "__file__": SCRIPT}})
'''


def read_template():
    if not os.path.exists(SUBMIT_TEMPLATE):
        raise SystemExit("Template '%s' not found (run this script from the "
                         "ScratchSimulation directory)." % SUBMIT_TEMPLATE)
    with open(SUBMIT_TEMPLATE, "rb") as f:
        raw = f.read()
    if b"run_parameter_study" not in raw:
        raise SystemExit("'%s' does not contain the word 'run_parameter_study' "
                         "-- nothing to substitute." % SUBMIT_TEMPLATE)
    return raw


def wrapper_cpus(raw):
    """Read the '-c N' of the wrapper line so the Abaqus CPU count follows
    submit.sh automatically (cpus= token)."""
    m = re.search(rb"run_parameter_study", raw)
    line = raw[:m.start()].rsplit(b"\n", 1)[-1] + raw[m.start():].split(b"\n", 1)[0]
    m = re.search(rb"-c\s+(\d+)", line)
    return int(m.group(1)) if m else None


def expand_jobs():
    """JOBS entries -> list of (label, tokens). 'material' is split.
    Validates tokens and rejects duplicate labels before any submission, so a
    typo (bad family, or the same (study, family) twice -> same output dir)
    fails loudly here instead of crashing / overwriting inside a SLURM job."""
    out = []
    for entry in JOBS:
        if len(entry) != 2:
            raise SystemExit("Bad JOBS entry %r: expected (study, family)." % (entry,))
        study, family = entry
        if study not in _VALID_STUDIES:
            raise SystemExit("Unknown study '%s' in JOBS. Valid: %s"
                             % (study, ", ".join(_VALID_STUDIES)))
        if family not in _VALID_FAMILIES:
            raise SystemExit("Unknown family '%s' in JOBS. Valid: %s"
                             % (family, ", ".join(_VALID_FAMILIES)))
        if study == "material" and SWEEP_JOBS > 1:
            for i in range(SWEEP_JOBS):
                label = "%s_%s_c%03dof%03d" % (study, family, i, SWEEP_JOBS)
                out.append((label, [study, family, "%d/%d" % (i, SWEEP_JOBS)]))
        else:
            out.append(("%s_%s" % (study, family), [study, family]))

    labels = [lbl for lbl, _ in out]
    dups = sorted(set(l for l in labels if labels.count(l) > 1))
    if dups:
        raise SystemExit(
            "Duplicate job label(s) %s: the same (study, family) appears twice "
            "in JOBS, which would share an output directory. Use distinct "
            "entries, or add a tag to tell them apart." % ", ".join(dups))
    return out


def main():
    raw = read_template()
    cpus = wrapper_cpus(raw)
    here = os.path.abspath(os.path.dirname(os.path.abspath(__file__)))
    script = os.path.join(here, "run_parameter_study.py")

    jobs = expand_jobs()
    print(">>> %d job(s) to submit (template: %s%s)"
          % (len(jobs), SUBMIT_TEMPLATE,
             ", -c %d detected -> cpus token" % cpus if cpus else ""))

    for label, tokens in jobs:
        if cpus:
            tokens = tokens + ["cpus=%d" % cpus]

        # 1. driver
        driver = "job_%s.py" % label
        with open(os.path.join(here, driver), "w") as f:
            f.write(DRIVER_TEMPLATE.format(label=label, tokens=tokens, script=script))

        # 2. submit script = your submit.sh with the word substituted.
        # Line endings are normalised to LF: the CRLF of the template leaves a
        # stray '\r' argument after the script name (caught in testing) that
        # only works if the site wrapper happens to tolerate it.
        submit = "submit_%s.sh" % label
        body = raw.replace(b"\r\n", b"\n").replace(b"\r", b"\n")
        body = body.replace(b"run_parameter_study", driver[:-3].encode())
        with open(os.path.join(here, submit), "wb") as f:
            f.write(body)

        # 3. sbatch, exactly like your manual workflow
        cmd = ["sbatch", submit]
        print("  [%s]  %s" % (label, " ".join(cmd)))
        if not DRY_RUN:
            rc = subprocess.call(cmd, cwd=here)
            if rc != 0:
                print("  !! sbatch returned %d for %s" % (rc, label))

    if DRY_RUN:
        print(">>> DRY_RUN: files generated, nothing submitted.")
    return 0


if __name__ == "__main__":
    sys.exit(main())